- name: Setup Nginx on web Server
  hosts: WebServer
  become: yes
  vars_files:
    - vars.yml
  roles:
    - deploy_nginx

- name: Setup Tomcat on App Server
  hosts: AppServer
  become: yes
  vars_files:
    - tomcat_vars.yml
  roles:
    - deploy_tomcat