- name: Setup Web server
  hosts: webserver
  # hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install nginx 
      apt:
        name: nginx
        update_cache: yes
        state: latest

    - name: Deploy Template
      template:
        src: appserver.j2
        dest: /etc/nginx/sites-available/appserver

    - name: Enable Routing
      file:
        src: /etc/nginx/sites-available/appserver
        dest: /etc/nginx/sites-enabled/appserver
        state: link

    - name: Delete Default file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Start nginx Service
      service:
        name: nginx
        state: restarted
        enabled: yes